### ISSUE TITLE
How to use this Delphi binding with SciterJS (use JavaScript instead of TIScript)

### ISSUE THREAD

**Issue by mercibac** [gxlmyacc/sciter4d#4]
Thanks for all the effort you've put in this Delphi sciter binding. 
It's working perfectly, without too much configurations.

Is there a way to use this binding with JavaScript instead of TIScript ?

**Comment by gxlmyacc** [comment]
this verion of Sciter which used by sciter4d only support tiscript. I heard that the latest version of Sciter seems to be able to use JavaScript, but now I no longer use Delphi and this project is basically not maintained. If you are interested, you can try forking a branch to support the latest version of the Sciter

**Comment by mercibac** [comment]
Okay. I understand. 
I will adapt it in order to support JavaScript scripting.

Thank you for the feedback !

**Comment by mercibac** [comment]
> this verion of Sciter which used by sciter4d only support tiscript. I heard that the latest version of Sciter seems to be able to use JavaScript, but now I no longer use Delphi and this project is basically not maintained. If you are interested, you can try forking a branch to support the latest version of the Sciter

I've founded Delphi(FMX) and Sciter to be 2 effective solutions for modern Desktop Software Development ...

I would like to know what are the alternative solutions that you use when developing Desktop Softwares.

**Comment by gxlmyacc** [comment]
I won't be working on developing client software now. I am currently working on front-end development. 
Nowadays, there are many applications that use web technology to develop client softwares, such as electronjs and NW.js. I would rather recommend these solutions.
Alternatively, you can consider using cef/dcef as a client software: https://github.com/hgourvest/dcef3
